// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app.proto

package com.ciy.device_center.proto;

public final class AppProto {
  private AppProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Info)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 设备唯一识别码
     * </pre>
     *
     * <code>string device_code = 1;</code>
     * @return The deviceCode.
     */
    java.lang.String getDeviceCode();
    /**
     * <pre>
     * 设备唯一识别码
     * </pre>
     *
     * <code>string device_code = 1;</code>
     * @return The bytes for deviceCode.
     */
    com.google.protobuf.ByteString
        getDeviceCodeBytes();

    /**
     * <pre>
     * 设备名称
     * </pre>
     *
     * <code>string device_name = 2;</code>
     * @return The deviceName.
     */
    java.lang.String getDeviceName();
    /**
     * <pre>
     * 设备名称
     * </pre>
     *
     * <code>string device_name = 2;</code>
     * @return The bytes for deviceName.
     */
    com.google.protobuf.ByteString
        getDeviceNameBytes();

    /**
     * <pre>
     * 设备类型(android:1  ios:2)
     * </pre>
     *
     * <code>int32 device_type = 3;</code>
     * @return The deviceType.
     */
    int getDeviceType();

    /**
     * <pre>
     * 应用名称
     * </pre>
     *
     * <code>string application_name = 4;</code>
     * @return The applicationName.
     */
    java.lang.String getApplicationName();
    /**
     * <pre>
     * 应用名称
     * </pre>
     *
     * <code>string application_name = 4;</code>
     * @return The bytes for applicationName.
     */
    com.google.protobuf.ByteString
        getApplicationNameBytes();

    /**
     * <pre>
     * 导向的ip
     * </pre>
     *
     * <code>string address = 5;</code>
     * @return The address.
     */
    java.lang.String getAddress();
    /**
     * <pre>
     * 导向的ip
     * </pre>
     *
     * <code>string address = 5;</code>
     * @return The bytes for address.
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <pre>
     * 导向的端口号
     * </pre>
     *
     * <code>int32 port = 6;</code>
     * @return The port.
     */
    int getPort();
  }
  /**
   * Protobuf type {@code Info}
   */
  public  static final class Info extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Info)
      InfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Info.newBuilder() to construct.
    private Info(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Info() {
      deviceCode_ = "";
      deviceName_ = "";
      applicationName_ = "";
      address_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Info();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Info(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              deviceCode_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              deviceName_ = s;
              break;
            }
            case 24: {

              deviceType_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              applicationName_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              address_ = s;
              break;
            }
            case 48: {

              port_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ciy.device_center.proto.AppProto.internal_static_Info_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ciy.device_center.proto.AppProto.internal_static_Info_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ciy.device_center.proto.AppProto.Info.class, com.ciy.device_center.proto.AppProto.Info.Builder.class);
    }

    public static final int DEVICE_CODE_FIELD_NUMBER = 1;
    private volatile java.lang.Object deviceCode_;
    /**
     * <pre>
     * 设备唯一识别码
     * </pre>
     *
     * <code>string device_code = 1;</code>
     * @return The deviceCode.
     */
    public java.lang.String getDeviceCode() {
      java.lang.Object ref = deviceCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceCode_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 设备唯一识别码
     * </pre>
     *
     * <code>string device_code = 1;</code>
     * @return The bytes for deviceCode.
     */
    public com.google.protobuf.ByteString
        getDeviceCodeBytes() {
      java.lang.Object ref = deviceCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICE_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object deviceName_;
    /**
     * <pre>
     * 设备名称
     * </pre>
     *
     * <code>string device_name = 2;</code>
     * @return The deviceName.
     */
    public java.lang.String getDeviceName() {
      java.lang.Object ref = deviceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 设备名称
     * </pre>
     *
     * <code>string device_name = 2;</code>
     * @return The bytes for deviceName.
     */
    public com.google.protobuf.ByteString
        getDeviceNameBytes() {
      java.lang.Object ref = deviceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICE_TYPE_FIELD_NUMBER = 3;
    private int deviceType_;
    /**
     * <pre>
     * 设备类型(android:1  ios:2)
     * </pre>
     *
     * <code>int32 device_type = 3;</code>
     * @return The deviceType.
     */
    public int getDeviceType() {
      return deviceType_;
    }

    public static final int APPLICATION_NAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object applicationName_;
    /**
     * <pre>
     * 应用名称
     * </pre>
     *
     * <code>string application_name = 4;</code>
     * @return The applicationName.
     */
    public java.lang.String getApplicationName() {
      java.lang.Object ref = applicationName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        applicationName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 应用名称
     * </pre>
     *
     * <code>string application_name = 4;</code>
     * @return The bytes for applicationName.
     */
    public com.google.protobuf.ByteString
        getApplicationNameBytes() {
      java.lang.Object ref = applicationName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        applicationName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDRESS_FIELD_NUMBER = 5;
    private volatile java.lang.Object address_;
    /**
     * <pre>
     * 导向的ip
     * </pre>
     *
     * <code>string address = 5;</code>
     * @return The address.
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 导向的ip
     * </pre>
     *
     * <code>string address = 5;</code>
     * @return The bytes for address.
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 6;
    private int port_;
    /**
     * <pre>
     * 导向的端口号
     * </pre>
     *
     * <code>int32 port = 6;</code>
     * @return The port.
     */
    public int getPort() {
      return port_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDeviceCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, deviceCode_);
      }
      if (!getDeviceNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, deviceName_);
      }
      if (deviceType_ != 0) {
        output.writeInt32(3, deviceType_);
      }
      if (!getApplicationNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, applicationName_);
      }
      if (!getAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, address_);
      }
      if (port_ != 0) {
        output.writeInt32(6, port_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDeviceCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, deviceCode_);
      }
      if (!getDeviceNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, deviceName_);
      }
      if (deviceType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, deviceType_);
      }
      if (!getApplicationNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, applicationName_);
      }
      if (!getAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, address_);
      }
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, port_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ciy.device_center.proto.AppProto.Info)) {
        return super.equals(obj);
      }
      com.ciy.device_center.proto.AppProto.Info other = (com.ciy.device_center.proto.AppProto.Info) obj;

      if (!getDeviceCode()
          .equals(other.getDeviceCode())) return false;
      if (!getDeviceName()
          .equals(other.getDeviceName())) return false;
      if (getDeviceType()
          != other.getDeviceType()) return false;
      if (!getApplicationName()
          .equals(other.getApplicationName())) return false;
      if (!getAddress()
          .equals(other.getAddress())) return false;
      if (getPort()
          != other.getPort()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEVICE_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceCode().hashCode();
      hash = (37 * hash) + DEVICE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceName().hashCode();
      hash = (37 * hash) + DEVICE_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceType();
      hash = (37 * hash) + APPLICATION_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getApplicationName().hashCode();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ciy.device_center.proto.AppProto.Info parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ciy.device_center.proto.AppProto.Info parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ciy.device_center.proto.AppProto.Info parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ciy.device_center.proto.AppProto.Info parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ciy.device_center.proto.AppProto.Info parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ciy.device_center.proto.AppProto.Info parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ciy.device_center.proto.AppProto.Info parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ciy.device_center.proto.AppProto.Info parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ciy.device_center.proto.AppProto.Info parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ciy.device_center.proto.AppProto.Info parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ciy.device_center.proto.AppProto.Info parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ciy.device_center.proto.AppProto.Info parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ciy.device_center.proto.AppProto.Info prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Info}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Info)
        com.ciy.device_center.proto.AppProto.InfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ciy.device_center.proto.AppProto.internal_static_Info_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ciy.device_center.proto.AppProto.internal_static_Info_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ciy.device_center.proto.AppProto.Info.class, com.ciy.device_center.proto.AppProto.Info.Builder.class);
      }

      // Construct using com.ciy.device_center.proto.AppProto.Info.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        deviceCode_ = "";

        deviceName_ = "";

        deviceType_ = 0;

        applicationName_ = "";

        address_ = "";

        port_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ciy.device_center.proto.AppProto.internal_static_Info_descriptor;
      }

      @java.lang.Override
      public com.ciy.device_center.proto.AppProto.Info getDefaultInstanceForType() {
        return com.ciy.device_center.proto.AppProto.Info.getDefaultInstance();
      }

      @java.lang.Override
      public com.ciy.device_center.proto.AppProto.Info build() {
        com.ciy.device_center.proto.AppProto.Info result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ciy.device_center.proto.AppProto.Info buildPartial() {
        com.ciy.device_center.proto.AppProto.Info result = new com.ciy.device_center.proto.AppProto.Info(this);
        result.deviceCode_ = deviceCode_;
        result.deviceName_ = deviceName_;
        result.deviceType_ = deviceType_;
        result.applicationName_ = applicationName_;
        result.address_ = address_;
        result.port_ = port_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ciy.device_center.proto.AppProto.Info) {
          return mergeFrom((com.ciy.device_center.proto.AppProto.Info)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ciy.device_center.proto.AppProto.Info other) {
        if (other == com.ciy.device_center.proto.AppProto.Info.getDefaultInstance()) return this;
        if (!other.getDeviceCode().isEmpty()) {
          deviceCode_ = other.deviceCode_;
          onChanged();
        }
        if (!other.getDeviceName().isEmpty()) {
          deviceName_ = other.deviceName_;
          onChanged();
        }
        if (other.getDeviceType() != 0) {
          setDeviceType(other.getDeviceType());
        }
        if (!other.getApplicationName().isEmpty()) {
          applicationName_ = other.applicationName_;
          onChanged();
        }
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          onChanged();
        }
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ciy.device_center.proto.AppProto.Info parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ciy.device_center.proto.AppProto.Info) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object deviceCode_ = "";
      /**
       * <pre>
       * 设备唯一识别码
       * </pre>
       *
       * <code>string device_code = 1;</code>
       * @return The deviceCode.
       */
      public java.lang.String getDeviceCode() {
        java.lang.Object ref = deviceCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deviceCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 设备唯一识别码
       * </pre>
       *
       * <code>string device_code = 1;</code>
       * @return The bytes for deviceCode.
       */
      public com.google.protobuf.ByteString
          getDeviceCodeBytes() {
        java.lang.Object ref = deviceCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 设备唯一识别码
       * </pre>
       *
       * <code>string device_code = 1;</code>
       * @param value The deviceCode to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 设备唯一识别码
       * </pre>
       *
       * <code>string device_code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeviceCode() {
        
        deviceCode_ = getDefaultInstance().getDeviceCode();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 设备唯一识别码
       * </pre>
       *
       * <code>string device_code = 1;</code>
       * @param value The bytes for deviceCode to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object deviceName_ = "";
      /**
       * <pre>
       * 设备名称
       * </pre>
       *
       * <code>string device_name = 2;</code>
       * @return The deviceName.
       */
      public java.lang.String getDeviceName() {
        java.lang.Object ref = deviceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deviceName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 设备名称
       * </pre>
       *
       * <code>string device_name = 2;</code>
       * @return The bytes for deviceName.
       */
      public com.google.protobuf.ByteString
          getDeviceNameBytes() {
        java.lang.Object ref = deviceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 设备名称
       * </pre>
       *
       * <code>string device_name = 2;</code>
       * @param value The deviceName to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 设备名称
       * </pre>
       *
       * <code>string device_name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeviceName() {
        
        deviceName_ = getDefaultInstance().getDeviceName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 设备名称
       * </pre>
       *
       * <code>string device_name = 2;</code>
       * @param value The bytes for deviceName to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceName_ = value;
        onChanged();
        return this;
      }

      private int deviceType_ ;
      /**
       * <pre>
       * 设备类型(android:1  ios:2)
       * </pre>
       *
       * <code>int32 device_type = 3;</code>
       * @return The deviceType.
       */
      public int getDeviceType() {
        return deviceType_;
      }
      /**
       * <pre>
       * 设备类型(android:1  ios:2)
       * </pre>
       *
       * <code>int32 device_type = 3;</code>
       * @param value The deviceType to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceType(int value) {
        
        deviceType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 设备类型(android:1  ios:2)
       * </pre>
       *
       * <code>int32 device_type = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeviceType() {
        
        deviceType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object applicationName_ = "";
      /**
       * <pre>
       * 应用名称
       * </pre>
       *
       * <code>string application_name = 4;</code>
       * @return The applicationName.
       */
      public java.lang.String getApplicationName() {
        java.lang.Object ref = applicationName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          applicationName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 应用名称
       * </pre>
       *
       * <code>string application_name = 4;</code>
       * @return The bytes for applicationName.
       */
      public com.google.protobuf.ByteString
          getApplicationNameBytes() {
        java.lang.Object ref = applicationName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          applicationName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 应用名称
       * </pre>
       *
       * <code>string application_name = 4;</code>
       * @param value The applicationName to set.
       * @return This builder for chaining.
       */
      public Builder setApplicationName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        applicationName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 应用名称
       * </pre>
       *
       * <code>string application_name = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearApplicationName() {
        
        applicationName_ = getDefaultInstance().getApplicationName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 应用名称
       * </pre>
       *
       * <code>string application_name = 4;</code>
       * @param value The bytes for applicationName to set.
       * @return This builder for chaining.
       */
      public Builder setApplicationNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        applicationName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <pre>
       * 导向的ip
       * </pre>
       *
       * <code>string address = 5;</code>
       * @return The address.
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 导向的ip
       * </pre>
       *
       * <code>string address = 5;</code>
       * @return The bytes for address.
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 导向的ip
       * </pre>
       *
       * <code>string address = 5;</code>
       * @param value The address to set.
       * @return This builder for chaining.
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 导向的ip
       * </pre>
       *
       * <code>string address = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 导向的ip
       * </pre>
       *
       * <code>string address = 5;</code>
       * @param value The bytes for address to set.
       * @return This builder for chaining.
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        address_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <pre>
       * 导向的端口号
       * </pre>
       *
       * <code>int32 port = 6;</code>
       * @return The port.
       */
      public int getPort() {
        return port_;
      }
      /**
       * <pre>
       * 导向的端口号
       * </pre>
       *
       * <code>int32 port = 6;</code>
       * @param value The port to set.
       * @return This builder for chaining.
       */
      public Builder setPort(int value) {
        
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 导向的端口号
       * </pre>
       *
       * <code>int32 port = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearPort() {
        
        port_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Info)
    }

    // @@protoc_insertion_point(class_scope:Info)
    private static final com.ciy.device_center.proto.AppProto.Info DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ciy.device_center.proto.AppProto.Info();
    }

    public static com.ciy.device_center.proto.AppProto.Info getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Info>
        PARSER = new com.google.protobuf.AbstractParser<Info>() {
      @java.lang.Override
      public Info parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Info(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Info> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Info> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ciy.device_center.proto.AppProto.Info getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Info_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Info_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tapp.proto\"~\n\004Info\022\023\n\013device_code\030\001 \001(\t" +
      "\022\023\n\013device_name\030\002 \001(\t\022\023\n\013device_type\030\003 \001" +
      "(\005\022\030\n\020application_name\030\004 \001(\t\022\017\n\007address\030" +
      "\005 \001(\t\022\014\n\004port\030\006 \001(\005B\'\n\033com.ciy.device_ce" +
      "nter.protoB\010AppProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Info_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Info_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Info_descriptor,
        new java.lang.String[] { "DeviceCode", "DeviceName", "DeviceType", "ApplicationName", "Address", "Port", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
